# Be sure to update the following before each run
<a href='#reporting month'>Reporting month in excel creation></a>

In [1]:
import pandas as pd
dff = pd.read_csv('Data/201907/worc-families.csv')
dff = pd.DataFrame(dff)

In [2]:
dff = dff.rename({'tem21a_amt':'cash & cash equivalents_amount',
                 'item21b_nbr_mth':'cash & cash equivalents_nbr_month',
                 'item22a_amt':'tanf child care_amount',
                 'item22b_child_cover':'tanf child care_children_covered',
                 'item22c_nbr_mth':'tanf child care_nbr_months',
                 'item23a_amt':'transportation_amount',
                 'item23b_nbr_mth':'transportation_nbr_months',
                 'item24a_amt':'transitional services_amount',
                 'item24b_nbr_mth':'transitional services_nbr_months',
                 'item25a_amt':'other_amount',
                 'item25b_nbr_mth':'other_nbr_months',
                 'item26a_sanc_red':'reason for amount of reduction_sanction reduction_amount',
                 'item26a_work_req':'reason for amount of reduction_work requirements sanction',
                 'item26a_no_hsd':'reason for amount of reduction_Family Sanction for an Adult with No High School Diploma or Equivalent',
                 'item26a_teen_parent':'reason for amount of reduction_Sanction for Teen Parent not Attending School',
                 'item26a_chid_sup':'reason for amount of reduction_Non-Cooperation with Child Support',
                 'item26a_resp_plan':'reason for amount of reduction_Failure to Comply with an Individual Responsibility Plan',
                 'item26a_other':'reason for amount of reduction_Other Sanction',
                 'item26b_recoup':'reason for amount of reduction_Recoupment of Prior Overpayment',
                 'item26c_other_red':'other_other total reduction amount:',
                 'item26c_family_cap':'other_Family Cap',
                 'item26c_red_lgth_assist':'other_Reduction Based on Length of Receipt of Assistance',
                 'item26c_other_non_sanc':'Other, Non-sanction'},axis='columns')

In [3]:
# Funding Stream

dff['funding_stream'] = ['Funded, in whole or in part, with Federal TANF block grant funds. \
This includes programs funded with commingled State and Federal funds.' if x==1
                        else('Funded entirely from State-only funds (segregated State TANF \
                        expenditures) which are subject to most, but not all, TANF rules' if x==2
                            else('Not Found')) for x in dff['funding_stream']]

In [4]:
# Disposition

dff['disposition'] = ['Data collection completed' if x==1
                     else('Not subject to data collection/listed in error' if x==2
                         else('Not Found')) for x in dff['disposition']]

In [5]:
# New Applicant

dff['new_applicant'] = ['Yes, a newly-approved application' if x==1
                       else('Not newly-approved application' if x==2
                           else('Not Found')) for x in dff['new_applicant']]

In [6]:
# Type of Family for Work Participation

dff['family_type'] = ['Family included only in overall work participation rate \
(i.e., family includes one or more workeligible individuals but does not meet definition of a twoparent family' if x==1                                                
                      else('Two-Parent Family included in both the overall and\
                      two-parent work participation rates (i.e., family includes\
                      two work-eligible parents and meets the definition of a two-parent family)' if x==2                       
                           else('Family with no work-eligible individual' if x==3
                                else 'Not found')) for x in dff['family_type']]

In [7]:
# Receives Subsidized Housing

dff['subsid_housing'] = ['Public housing' if x==1
                        else('Rent subsidy' if x==2
                            else('No housing subsidy' if x==3
                                else('Not Found'))) for x in dff['subsid_housing']]

In [8]:
# Receives Medical Assistance

dff['medical_assist'] = [' Yes, enrolled in Medicaid and/or CHIP' if x==1
                        else('Does not receive Medical Assistance' if x==2
                            else('Not Found')) for x in dff['medical_assist']]

In [9]:
# Receives Food Stamps

dff['food_stamps'] = ['Yes, receives food stamp assistance' if x==1
                     else('Does not receive food stamp' if x==2
                         else('Not Found')) for x in dff['food_stamps']]

In [10]:
# Receives Subsidized Child Care

dff['subsid_child_care'] = ['Yes, receives child care funded entirely or in part with \
Federal funds (e.g., receives TANF, CCDF, SSBG, or other federally funded child care)' if x==1
                           else('Yes, receives child care funded entirely under a State, \
                           Tribal, and/or local program (i.e., no Federal funds used)' if x==2
                               else('No subsidized child care received' if x==3
                                   else('Not Found'))) for x in dff['subsid_child_care']]

In [11]:
# Work Requirements Sanction

dff['reason for amount of reduction_work requirements sanction'] = ['Yes' if x==1
                                                                   else('No' if x==2
                                                                   else('Not Found')) for x in dff['reason for amount of reduction_work requirements sanction']]

In [12]:
# Family Sanction for an Adult with No High School Diploma or Equivalent

dff['reason for amount of reduction_Family Sanction for an Adult with No High School Diploma or Equivalent'] = ['Yes' if x==1
                                                                   else('No' if x==2
                                                                   else('Not Found')) for x in dff['reason for amount of reduction_Family Sanction for an Adult with No High School Diploma or Equivalent']]

In [13]:
# Sanction for Teen Parent not Attending School

dff['reason for amount of reduction_Sanction for Teen Parent not Attending School'] = ['Yes' if x==1
                                                                   else('No' if x==2
                                                                   else('Not Found')) for x in dff['reason for amount of reduction_Sanction for Teen Parent not Attending School']]

In [14]:
# Non-Cooperation with Child Support

dff['reason for amount of reduction_Non-Cooperation with Child Support'] = ['Yes' if x==1
                                                                   else('No' if x==2
                                                                   else('Not Found')) for x in dff['reason for amount of reduction_Non-Cooperation with Child Support']]

In [15]:
# Failure to Comply with an Individual Responsibility Plan

dff['reason for amount of reduction_Failure to Comply with an Individual Responsibility Plan'] = ['Yes' if x==1
                                                                   else('No' if x==2
                                                                   else('Not Found')) for x in dff['reason for amount of reduction_Failure to Comply with an Individual Responsibility Plan']]

In [16]:
# Other Sanction

dff['reason for amount of reduction_Other Sanction'] = ['Yes' if x==1
                                                                   else('No' if x==2
                                                                   else('Not Found')) for x in dff['reason for amount of reduction_Other Sanction']]

In [17]:
# Family Cap

dff['other_Family Cap'] = ['Yes' if x==1
                           else('No' if x==2
                                else('Not Found')) for x in dff['other_Family Cap']]

In [18]:
# Reduction Based on Length of Receipt of Assistance

dff['other_Reduction Based on Length of Receipt of Assistance'] = ['Yes' if x==1
                                                                  else('No' if x==2
                                                                      else('Not Found')) for x in dff['other_Reduction Based on Length of Receipt of Assistance']]

In [19]:
# Other, Non-sanction

dff['Other, Non-sanction'] = ['Yes' if x==1
                           else('No' if x==2
                                else('Not Found')) for x in dff['Other, Non-sanction']]

In [20]:
# Is the TANF Family Exempt from the Federal Time-Limit Provisions

dff['exempt_time_limit'] = ['Family is not exempt from Federal time limit.' if x==1
                           else(' Yes, family is exempt from accrual of months and \
                           termination of assistance under the Federal five-year time\
                           limit for the reporting month because no headof-household \
                           or spouse of the head-of-household in the eligible family is receiving assistance.' if x==2
                               else('Yes, family is exempt from accrual of months under\
                               the Federal five-year time limit for the reporting month \
                               because assistance to family is funded entirely from \
                               State-only funds (See data element #8, Funding Stream, code 2.)' if x==3
                                   else('Yes, family is exempt from accrual of months \
                                   under the Federal five-year time limit for the reporting \
                                   month because the family is living in Indian country\
                                   or an Alaskan native village, where at least 50 percent \
                                   of the adults living in the Indian country or Alaskan native village are not employed.'if x==4
                                       else(' Code no longer in use' if x==5
                                           else('Yes, family is exempt from termination of assistance\
                                           under the Federal fiveyear time limit for the reporting month\
                                           because assistance to the family is funded entirely from \
                                           State-only funds (See data element #8, Funding Stream, code 2.)' if x==6
                                               else('Yes, family is exempt from termination of assistance \
                                               under the Federal fiveyear time limit for the reporting month \
                                               due to a hardship exemption, battery, or extreme cruelty \
                                               (i.e., victims of domestic violence who were not given a Federally \
                                               recognized domestic violence waiver).' if x==7
                                                   else(' Yes, family is exempt from termination of assistance under \
                                                   State policy for the reporting month based on a federally recognized \
                                                   good cause domestic violence waiver of time limits.' if x==8
                                                       else('Yes, family is exempt from termination of assistance under the \
                                                       Federal fiveyear time limit for the reporting month because the \
                                                       head-of-household or the spouse of the head-of-household is living \
                                                       in Indian country or an Alaskan native village, where at least 50 \
                                                       percent of whose adults are not employed.' if x==9
                                                           else('Code no longer in use' if x==10
                                                               else('Code no longer in use' if x==11
                                                                   else('Not Found'))))))))))) for x in dff['exempt_time_limit']]

In [21]:
# Is the TANF Family A New Child-Only Family?

dff['new_child_only_fam'] = ['Yes, a new child-only family' if x==1
                            else(' No, not a new child-only family'if x==2
                                else('Not Found')) for x in dff['new_child_only_fam']]

In [22]:
# adding prefix 201907_ to the column name

dff = dff.add_prefix('201907_')

<a id='reporting month'>Update Reporting Month in file name</a>

In [30]:
dff1 = dff.copy()

writer = pd.ExcelWriter('Data/worc_families_201907.xlsx')
dff1.to_excel(writer, index=False)
writer.save()

In [26]:
dff.loc[dff['201907_reason for amount of reduction_Other Sanction']=='Yes',('201907_case_number','201907_family_size')]

      201907_case_number  201907_family_size
1369             7989093                   3

In [30]:
dff.loc[dff['201907_case_number']==8000804]

,201907_id,201907_category,201907_reporting_month,201907_case_number,201907_county_fips_code,201907_stratum,201907_zip_code,201907_funding_stream,201907_disposition,201907_new_applicant,...,201907_new_child_only_fam,201907_worker_id,201907_case_manager,201907_area,201907_created_by,201907_updated_by,201907_created_at,201907_updated_at,201907_ans_county,201907_local_office
1263,431651,20,201907,8000804,107,99,72390,"Funded, in whole or in part, with Federal TANF...",Data collection completed,Not newly-approved application,...,"No, not a new child-only family",9308,0,99,555,555,8/9/2019 19:00,8/9/2019 19:00,3970,13

In [31]:
dff.loc[dff['201907_case_number']==8000804,['201907_family_type']]

     201907_family_type
1263          Not found

In [32]:
dff.loc[dff['201907_family_type']==0]

Empty DataFrame
Columns: [201907_id, 201907_category, 201907_reporting_month, 201907_case_number, 201907_county_fips_code, 201907_stratum, 201907_zip_code, 201907_funding_stream, 201907_disposition, 201907_new_applicant, 201907_family_size, 201907_family_type, 201907_subsid_housing, 201907_medical_assist, 201907_food_stamps, 201907_food_stamps_amt, 201907_subsid_child_care, 201907_subsid_child_care_amt, 201907_child_support_amt, 201907_cash_resource_amt, 201907_cash & cash equivalents_amount, 201907_cash & cash equivalents_nbr_month, 201907_tanf child care_amount, 201907_tanf child care_children_covered, 201907_tanf child care_nbr_months, 201907_transportation_amount, 201907_transportation_nbr_months, 201907_transitional services_amount, 201907_transitional services_nbr_months, 201907_other_amount, 201907_other_nbr_months, 201907_reason for amount of reduction_sanction reduction_amount, 201907_reason for amount of reduction_work requirements sanction, 201907_reason for amount of reduction_Family Sanction for an Adult with No High School Diploma or Equivalent, 201907_reason for amount of reduction_Sanction for Teen Parent not Attending School, 201907_reason for amount of reduction_Non-Cooperation with Child Support, 201907_reason for amount of reduction_Failure to Comply with an Individual Responsibility Plan, 201907_reason for amount of reduction_Other Sanction, 201907_reason for amount of reduction_Recoupment of Prior Overpayment, 201907_other_other total reduction amount:, 201907_other_Family Cap, 201907_other_Reduction Based on Length of Receipt of Assistance, 201907_Other, Non-sanction, 201907_waiver_grps, 201907_exempt_time_limit, 201907_new_child_only_fam, 201907_worker_id, 201907_case_manager, 201907_area, 201907_created_by, 201907_updated_by, 201907_created_at, 201907_updated_at, 201907_ans_county, 201907_local_office]
Index: []

[0 rows x 55 columns]

# this works do not delete!!
## apply .describe() to get statistical data

In [37]:
# Filtering just the columns that ends with amt, amount, nbr_months

dff_amount = dff.filter(regex='amt$|amount$|nbr_months$', axis='columns')
dff_amount



#df.filter(regex=r'^foo\.', axis=1) #column name starts with foo

,201907_food_stamps_amt,201907_subsid_child_care_amt,201907_child_support_amt,201907_cash_resource_amt,201907_cash & cash equivalents_amount,201907_tanf child care_amount,201907_tanf child care_nbr_months,201907_transportation_amount,201907_transportation_nbr_months,201907_transitional services_amount,201907_transitional services_nbr_months,201907_other_amount,201907_other_nbr_months,201907_reason for amount of reduction_sanction reduction_amount
0,95,0,0,0,153,0,0,0,0,0,0,0,0,0.0
1,0,0,0,0,153,0,0,0,0,0,0,0,0,0.0
2,80,0,0,0,204,0,0,0,0,0,0,0,0,0.0
3,8,0,0,0,153,0,0,0,0,0,0,0,0,0.0
4,0,0,0,0,204,0,0,0,0,0,0,0,0,0.0
5,177,0,0,0,204,0,0,0,0,0,0,0,0,0.0
6,72,0,0,0,204,0,0,0,0,0,0,0,0,0.0
7,86,0,0,0,204,0,0,0,0,0,0,0,0,0.0
8,56,0,0,0,204,0,0,0,0,0,0,0,0,0.0
9,31,0,0,0,204,0,0,0,0,0,0,0,0,0.0
10,26,0,0,0,204,0,0,0,0,0,0,0,0,0.0
11,0,0,0,0,153,0,0,0,0,0,0,0,0,0.0
12,117,0,0,0,204,0,0,0,0,0,0,0,0,0.0
13,0,0,0,0,204,0,0,0,0,0,0,0,0,0.0
14,84,0,0,0,204,0,0,0,0,0,0,0,0,0.0
15,22,0,0,0,102,0,0,0,0,0,0,0,0,0.0
16,12,0,0,0,204,0,0,0,0,0,0,0,0,0.0
17,60,0,0,0,204,0,0,0,0,0,0,0,0,0.0
18,48,0,0,0,204,0,0,0,0,0,0,0,0,0.0
19,17,0,0,0,153,0,0,0,0,0,0,0,0,0.0
20,51,0,0,0,204,0,0,0,0,0,0,0,0,0.0
21,161,0,0,0,204,0,0,0,0,0,0,0,0,0.0
22,65,0,0,0,153,0,0,0,0,0,0,0,0,0.0
23,168,0,0,0,204,0,0,0,0,0,0,0,0,0.0
24,122,0,0,0,102,0,0,0,0,0,0,0,0,0.0
25,52,0,0,0,204,0,0,0,0,0,0,0,0,0.0
26,0,0,0,0,204,0,0,0,0,0,0,0,0,0.0
27,75,0,0,0,204,0,0,0,0,0,0,0,0,0.0
28,8,0,0,0,153,0,0,0,0,0,0,0,0,0.0
29,60,0,0,0,204,0,0,0,0,0,0,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2313,164,0,0,0,204,0,0,0,0,0,0,0,0,0.0
2314,0,0,0,0,162,0,0,0,0,0,0,0,0,0.0
2315,126,0,0,0,286,0,0,0,0,0,0,0,0,0.0
2316,141,0,0,0,162,0,0,0,0,0,0,0,0,0.0
2317,0,0,0,0,162,0,0,0,0,0,0,0,0,0.0
2318,152,0,0,0,247,0,0,0,0,0,0,0,0,0.0
2319,177,0,0,0,162,0,0,0,0,0,0,0,0,0.0
2320,177,0,0,0,162,0,0,0,0,0,0,0,0,0.0
2321,177,0,0,0,162,0,0,0,0,0,0,0,0,0.0
2322,161,0,0,0,204,0,0,0,0,0,0,0,0,0.0
2323,115,0,0,0,204,0,0,0,0,0,0,0,0,0.0
2324,177,0,0,0,162,0,0,0,0,0,0,0,0,0.0
2325,110,0,0,0,162,0,0,0,0,0,0,0,0,0.0
2326,87,0,0,0,286,0,0,0,0,0,0,0,0,0.0
2327,161,0,0,0,247,0,0,0,0,0,0,0,0,0.0
2328,100,0,0,0,162,0,0,0,0,0,0,0,0,0.0
2329,155,0,0,0,1,0,0,0,0,0,0,0,0,0.0
2330,152,0,0,0,162,0,0,0,0,0,0,0,0,0.0
2331,8,0,0,0,204,0,0,0,0,0,0,0,0,0.0
2332,8,0,0,0,81,0,0,0,0,0,0,0,0,0.0
2333,0,0,0,0,81,0,0,0,0,0,0,0,0,0.0
2334,119,0,0,0,162,0,0,0,0,0,0,0,0,0.0
2335,23,0,0,0,162,0,0,0,0,0,0,0,0,0.0
2336,85,0,0,0,162,0,0,0,0,0,0,0,0,0.0
2337,0,0,0,0,162,0,0,0,0,0,0,0,0,0.0
2338,139,0,0,0,247,0,0,0,0,0,0,0,0,0.0
2339,164,0,0,0,204,0,0,0,0,0,0,0,0,0.0
2340,168,0,0,0,204,0,0,0,0,0,0,0,0,0.0
2341,152,0,0,0,331,0,0,0,0,0,0,0,0,0.0
2342,161,0,0,0,162,0,0,0,0,0,0,0,0,0.0

In [38]:
k = dff_amount.describe()
writer = pd.ExcelWriter('Data/amt_nbrmonths_201907.xlsx')
k.to_excel(writer, index=False)
writer.save()

print(k)

       201907_food_stamps_amt  201907_subsid_child_care_amt  \
count             2343.000000                        2343.0
mean                95.575758                           0.0
std                 67.534304                           0.0
min                  0.000000                           0.0
25%                 13.500000                           0.0
50%                105.000000                           0.0
75%                161.000000                           0.0
max                192.000000                           0.0

       201907_child_support_amt  201907_cash_resource_amt  \
count                    2343.0                    2343.0
mean                        0.0                       0.0
std                         0.0                       0.0
min                         0.0                       0.0
25%                         0.0                       0.0
50%                         0.0                       0.0
75%                         0.0                       0.0
max                         0.0                       0.0

       201907_cash & cash equivalents_amount  201907_tanf child care_amount  \
count                            2343.000000                         2343.0
mean                              153.852753                            0.0
std                                60.453948                            0.0
min                                 0.000000                            0.0
25%                                81.000000                            0.0
50%                               162.000000                            0.0
75%                               204.000000                            0.0
max                               457.000000                            0.0

       201907_tanf child care_nbr_months  201907_transportation_amount  \
count                             2343.0                        2343.0
mean                                 0.0                           0.0
std                                  0.0                           0.0
min                                  0.0                           0.0
25%                                  0.0                           0.0
50%                                  0.0                           0.0
75%                                  0.0                           0.0
max                                  0.0                           0.0

       201907_transportation_nbr_months  201907_transitional services_amount  \
count                            2343.0                               2343.0
mean                                0.0                                  0.0
std                                 0.0                                  0.0
min                                 0.0                                  0.0
25%                                 0.0                                  0.0
50%                                 0.0                                  0.0
75%                                 0.0                                  0.0
max                                 0.0                                  0.0

       201907_transitional services_nbr_months  201907_other_amount  \
count                                   2343.0               2343.0
mean                                       0.0                  0.0
std                                        0.0                  0.0
min                                        0.0                  0.0
25%                                        0.0                  0.0
50%                                        0.0                  0.0
75%                                        0.0                  0.0
max                                        0.0                  0.0

       201907_other_nbr_months  \
count                   2343.0
mean                       0.0
std                        0.0
min                        0.0
25%                        0.0
50%                        0.0
75%                        0.0
max                        0.0

       201907_reason for amount of reduction_sanction reduction_amount
count                                        2342.000000
mean                                            9.149872
std                                            34.240913
min                                             0.000000
25%                                             0.000000
50%                                             0.000000
75%                                             0.000000
max                                           331.000000

In [39]:
dff.shape

(2343, 55)

In [43]:
for ind,column in enumerate(dff_cat):
    print(ind,column)

0 201907_id
1 201907_category
2 201907_reporting_month
3 201907_case_number
4 201907_county_fips_code
5 201907_stratum
6 201907_zip_code
7 201907_funding_stream
8 201907_disposition
9 201907_new_applicant
10 201907_family_size
11 201907_family_type
12 201907_subsid_housing
13 201907_medical_assist
14 201907_food_stamps
15 201907_subsid_child_care
16 201907_cash & cash equivalents_nbr_month
17 201907_tanf child care_children_covered
18 201907_reason for amount of reduction_work requirements sanction
19 201907_reason for amount of reduction_Family Sanction for an Adult with No High School Diploma or Equivalent
20 201907_reason for amount of reduction_Sanction for Teen Parent not Attending School
21 201907_reason for amount of reduction_Non-Cooperation with Child Support
22 201907_reason for amount of reduction_Failure to Comply with an Individual Responsibility Plan
23 201907_reason for amount of reduction_Other Sanction
24 201907_reason for amount of reduction_Recoupment of Prior Overpayment
25 201907_other_other total reduction amount:
26 201907_other_Family Cap
27 201907_other_Reduction Based on Length of Receipt of Assistance
28 201907_Other, Non-sanction
29 201907_waiver_grps
30 201907_exempt_time_limit
31 201907_new_child_only_fam
32 201907_worker_id
33 201907_case_manager
34 201907_area
35 201907_created_by
36 201907_updated_by
37 201907_created_at
38 201907_updated_at
39 201907_ans_county
40 201907_local_office

# category only

In [42]:
dff_cat =dff.drop(dff_amount,axis=1)
dff_cat.head(2)

,201907_id,201907_category,201907_reporting_month,201907_case_number,201907_county_fips_code,201907_stratum,201907_zip_code,201907_funding_stream,201907_disposition,201907_new_applicant,...,201907_new_child_only_fam,201907_worker_id,201907_case_manager,201907_area,201907_created_by,201907_updated_by,201907_created_at,201907_updated_at,201907_ans_county,201907_local_office
0,429419,84,201907,7984407,143,99,72764,"Funded, in whole or in part, with Federal TANF...",Data collection completed,Not newly-approved application,...,"No, not a new child-only family",572,1005,99,555,555,8/9/2019 19:00,8/9/2019 19:00,3992,9
1,429420,84,201907,7983687,119,99,72113,"Funded, in whole or in part, with Federal TANF...",Data collection completed,Not newly-approved application,...,"No, not a new child-only family",572,1001,99,555,555,8/9/2019 19:00,8/9/2019 19:00,3976,18

In [44]:
dff_cat1 = dff_cat.drop(dff_cat.iloc[:,0:8],axis=1)
#dff_cat1.head(2)
dff_cat2 = dff_cat1.drop((dff_cat1.iloc[:,-9:]),axis=1)
dff_cat2.head(2)


writer = pd.ExcelWriter('Data/worc_families_category.xlsx')
dff_cat2.to_excel(writer, index=False)
writer.save()

In [56]:

for c in dff_cat2.columns:
    #print(dff[c].value_counts().to_frame())

    print(dff[c].value_counts().to_frame('count').rename_axis(c).reset_index())
       
    
    
    #print(dff[c].value_counts())

    print('--')

          201907_disposition  count
0  Data collection completed   2343
--
                201907_new_applicant  count
0     Not newly-approved application   2303
1  Yes, a newly-approved application     40
--
   201907_family_size  count
0                   2    925
1                   1    581
2                   3    507
3                   4    211
4                   5     75
5                   6     29
6                   7     13
7                   9      2
--
                                  201907_family_type  count
0            Family with no work-eligible individual   1142
1  Family included only in overall work participa...   1141
2  Two-Parent Family included in both the overall...     54
3                                          Not found      6
--
  201907_subsid_housing  count
0    No housing subsidy   2343
--
                    201907_medical_assist  count
0     Does not receive Medical Assistance   1565
1   Yes, enrolled in Medicaid and/or CHIP    778
--
                    201907_food_stamps  count
0  Yes, receives food stamp assistance   1815
1          Does not receive food stamp    528
--
            201907_subsid_child_care  count
0  No subsidized child care received   2343
--
    201907_cash & cash equivalents_nbr_month  count
0                                       24.0    979
1                                        2.0    171
2                                        3.0    143
3                                        1.0    143
4                                        4.0    124
5                                        5.0    108
6                                        6.0     89
7                                        7.0     78
8                                        8.0     78
9                                        9.0     60
10                                      10.0     50
11                                      11.0     48
12                                      12.0     40
13                                      13.0     33
14                                      14.0     32
15                                      17.0     28
16                                      18.0     20
17                                      15.0     19
18                                      16.0     19
19                                      19.0     17
20                                      21.0     16
21                                      20.0     15
22                                      22.0     14
23                                      23.0      8
24                                      27.0      3
25                                      25.0      2
26                                       0.0      2
27                                      29.0      1
28                                      36.0      1
29                                      37.0      1
--
   201907_tanf child care_children_covered  count
0                                        0   2343
--
  201907_reason for amount of reduction_work requirements sanction  count
0                                                 No                 2130
1                                                Yes                  213
--
  201907_reason for amount of reduction_Family Sanction for an Adult with No High School Diploma or Equivalent  \
0                                                 No

   count
0   2343
--
  201907_reason for amount of reduction_Sanction for Teen Parent not Attending School  \
0                                                 No
1                                                Yes

   count
0   2342
1      1
--
  201907_reason for amount of reduction_Non-Cooperation with Child Support  \
0                                                 No
1                                                Yes

   count
0   2247
1     96
--
  201907_reason for amount of reduction_Failure to Comply with an Individual Responsibility Plan  \
0                                                 No

   count
0   2343
--
  201907_reason for amount of reduction_Other Sanction  count
0                                                 No     2342
1                                                Yes        1
--
   201907_reason for amount of reduction_Recoupment of Prior Overpayment  \
0                                                  0

   count
0   2343
--
   201907_other_other total reduction amount:  count
0                                           0   2343
--
  201907_other_Family Cap  count
0                      No   2343
--
  201907_other_Reduction Based on Length of Receipt of Assistance  count
0                                                 No                2343
--
  201907_Other, Non-sanction  count
0                         No   2343
--
   201907_waiver_grps  count
0                   9   2343
--
                            201907_exempt_time_limit  count
0      Family is not exempt from Federal time limit.   1215
1   Yes, family is exempt from accrual of months ...   1128
--
          201907_new_child_only_fam  count
0   No, not a new child-only family   2329
1      Yes, a new child-only family     14
--

In [96]:
c = pd.read_excel('Data/worc_families_category.xlsx')
c.head(2)

,201907_disposition,201907_new_applicant,201907_family_size,201907_family_type,201907_subsid_housing,201907_medical_assist,201907_food_stamps,201907_subsid_child_care,201907_cash & cash equivalents_nbr_month,201907_tanf child care_children_covered,...,201907_reason for amount of reduction_Failure to Comply with an Individual Responsibility Plan,201907_reason for amount of reduction_Other Sanction,201907_reason for amount of reduction_Recoupment of Prior Overpayment,201907_other_other total reduction amount:,201907_other_Family Cap,201907_other_Reduction Based on Length of Receipt of Assistance,"201907_Other, Non-sanction",201907_waiver_grps,201907_exempt_time_limit,201907_new_child_only_fam
0,Data collection completed,Not newly-approved application,9,Family included only in overall work participa...,No housing subsidy,Does not receive Medical Assistance,"Yes, receives food stamp assistance",No subsidized child care received,3.0,0,...,No,No,0,0,No,No,No,9,Family is not exempt from Federal time limit.,"No, not a new child-only family"
1,Data collection completed,Not newly-approved application,4,Family included only in overall work participa...,No housing subsidy,Does not receive Medical Assistance,Does not receive food stamp,No subsidized child care received,4.0,0,...,No,No,0,0,No,No,No,9,Family is not exempt from Federal time limit.,"No, not a new child-only family"

In [59]:
for ind, column in enumerate(dff.columns):
    print(ind, column)

0 201907_id
1 201907_category
2 201907_reporting_month
3 201907_case_number
4 201907_county_fips_code
5 201907_stratum
6 201907_zip_code
7 201907_funding_stream
8 201907_disposition
9 201907_new_applicant
10 201907_family_size
11 201907_family_type
12 201907_subsid_housing
13 201907_medical_assist
14 201907_food_stamps
15 201907_food_stamps_amt
16 201907_subsid_child_care
17 201907_subsid_child_care_amt
18 201907_child_support_amt
19 201907_cash_resource_amt
20 201907_cash & cash equivalents_amount
21 201907_cash & cash equivalents_nbr_month
22 201907_tanf child care_amount
23 201907_tanf child care_children_covered
24 201907_tanf child care_nbr_months
25 201907_transportation_amount
26 201907_transportation_nbr_months
27 201907_transitional services_amount
28 201907_transitional services_nbr_months
29 201907_other_amount
30 201907_other_nbr_months
31 201907_reason for amount of reduction_sanction reduction_amount
32 201907_reason for amount of reduction_work requirements sanction
33 201907_reason for amount of reduction_Family Sanction for an Adult with No High School Diploma or Equivalent
34 201907_reason for amount of reduction_Sanction for Teen Parent not Attending School
35 201907_reason for amount of reduction_Non-Cooperation with Child Support
36 201907_reason for amount of reduction_Failure to Comply with an Individual Responsibility Plan
37 201907_reason for amount of reduction_Other Sanction
38 201907_reason for amount of reduction_Recoupment of Prior Overpayment
39 201907_other_other total reduction amount:
40 201907_other_Family Cap
41 201907_other_Reduction Based on Length of Receipt of Assistance
42 201907_Other, Non-sanction
43 201907_waiver_grps
44 201907_exempt_time_limit
45 201907_new_child_only_fam
46 201907_worker_id
47 201907_case_manager
48 201907_area
49 201907_created_by
50 201907_updated_by
51 201907_created_at
52 201907_updated_at
53 201907_ans_county
54 201907_local_office

In [60]:
df = pd.DataFrame({'1Country': ['FR', 'FR', 'GER','GER','IT','IT', 'FR','GER','IT'],
               '2City': ['Paris', 'Paris', 'Berlin', 'Berlin', 'Rome', 'Rome','Paris','Berlin','Rome'],
               'F1': ['A', 'B', 'C', 'B', 'B', 'C', 'A', 'B', 'C'],
               'F2': ['B', 'C', 'A', 'A', 'B', 'C', 'A', 'B', 'C'],
               'F3': ['C', 'A', 'B', 'C', 'C', 'C', 'A', 'B', 'C']})
df.groupby(['1Country', '2City']).agg({'F1': 'value_counts', 'F2': 'value_counts'})

               F1   F2
FR  Paris  A  2.0  1.0
           B  1.0  1.0
           C  NaN  1.0
GER Berlin A  NaN  2.0
           B  2.0  1.0
           C  1.0  NaN
IT  Rome   B  1.0  1.0
           C  2.0  2.0